services:
  backend:
    build: ./backend
    container_name: bilias-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    restart: always