services:
  frontend:
    build: ./frontend
    container_name: bilias-frontend
    ports:
      - '3000:3000'
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    networks:
      - app-net
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: bilias-backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgres://bilias:kernel21@db:5432/bilias
    networks:
      - app-net
    depends_on:
      - db

  db:
    build: ./BD
    container_name: bilias-db
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: bilias
      POSTGRES_PASSWORD: kernel21
      POSTGRES_DB: bilias
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  db-data:
